### ISSUE TITLE
Can I download atlas cli with specifying patch version for linux?

### ISSUE THREAD

**Issue by unknowingknow** [ariga/atlas#1183]
When to use `atlas` as [versioned migrations](https://entgo.io/docs/versioned-migrations) of `ent`,  it is used as a cli and a package.
I want to match the cli version with the package version. The latest version managed by `go module` is `v0.7.2` now, so I want to download the cli with `v0.7.2`

I have checked the following ways.

- docker
    - `0.7.2` tag is not found.
- release path
    - `https://release.ariga.io/atlas/atlas-linux-amd64-v0.7.2` path is not found.
- go install
    - It seems to be possible to install with `go install ariga.io/atlas/cmd/atlas@v0.7.2`, but the version information is not set because the build flag must be set manually.

**Comment by a8m** [comment]
Hey @unknowingknow, and thanks for raising this issue. 
The `atlas` and `cmd/atlas` modules are separated because we don't want to bring all CLI dependencies to the Atlas runtime packages (`ariga.io/atlas`). Therefore, the module hashes may be different, mainly because we don't release a CLI version the same as we update the `ariga.io/atlas` in Ent.

However, this should not be an issue because the `atlas/sql` package is used as the engine for generating migrations, and the CLI version is just used for executing them. I'll recommend you, use the latest stable version that exists on our website - https://atlasgo.io/getting-started#installation. 

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/zZ6sWVg6NT) if you still need help with this.
