### ISSUE TITLE
Move core functionality from cmd/* to sql/*

### ISSUE THREAD

**Issue by ceresdarkmatter** [ariga/atlas#1344]
While going through the documentation of Atlas I stumbled on this section: https://atlasgo.io/integrations/go-api
There it says that the core engine capabilities can be used as a go library / embedded as a module.

Unfortunately at the moment some very core features seems to be implemented in `cmd/*` - this makes trying to replicate the functionality of the CLI tool impossible.

For example - there is no way of reading a set of revisions from the DB revisions table as the `ent` implementation of the `sql/migrate.RevisionReadWriter` is not bundled with the `ariga.io/atlas` go module.

As far as I can tell the `ariga.io/atlas` go module basically packages / exposes the `sql/` directory from this repo and in the case of this example the implementation of `RevisionReadWriter` is `EntRevisions` inside `cmd/atlas/internal/migrate/migrate.go`

Could you please move the core functionality to the exported go module so that the main features of the CLI can be replicated programatically by using the Atlas go API / embedding Atlas as a go module?

**Comment by a8m** [comment]
Hey @ceresdarkmatter 👋 

Can you please elaborate on this use case? Like why not use the CLI directly to interact with the revisions table? If additional functionality is missing, please elaborate on it as well. Thanks 🙏

**Comment by ceresdarkmatter** [comment]
Hey @a8m - the use case is integrating a migrator directly as a library in an application - and strictly as a library.

This would be on par with what more mature migration frameworks in other languages are doing - like Flyway and Liquibase in Java for example.

The reason for not using the CLI is simple - the need to have the full control of the migration mechanism in process with fine grained control instead of external CLI tools. Also the possibility of migration run / validation every single time a DB connection is being initialised.

Short answer: not doable via CLI.

**Comment by a8m** [comment]
Thanks for the explanation, @ceresdarkmatter. 

> The reason for not using the CLI is simple - the need to have the full control of the migration mechanism in process with fine grained control instead of external CLI tools. 

Still, I'm not sure I understand the use case regarding product requirements. Would you mind giving specific examples, also elaborating on how you handle migrations today, and do you wish to use Atlas and for what?  If there's anything currently missing in Atlas, I'd like to know what, as it can help us improve this tool.

Exporting the entire functionality requires a lot of effort and also means committing to a specific API, and that's why all these questions.

**Comment by ceresdarkmatter** [comment]
Hey @a8m 

The requirements are simple: we want the migrations to be handled by the application itself, not using any external out-of process tools.

Unfortunately I cannot go into more detail but I am surprised that this seems controversial as it is one of the default approach of managing migrations in more established frameworks (like Flyway and Liquibase).

Specific example - verify that the DB is up to date and run the migrations if necessary every time an instance of the service is being started or each time a batch job that uses the exact same DB as the main (horizontally scaled) service is being run.

We are not running migrations at the moment - still searching for a mature tool for doing this in go and so far Atlas was the closest thing to the established tools in other languages. 
What is missing in Atlas is this - the possibility to replicate what the CLI does in the embeddable go library / module.

I am aware that some degree of effort is require for moving the functionality around - was Atlas envisioned as a CLI-only tool initially? I am asking this as a surprising amount of functionality is in the `cmd/` directory as opposed to the module / exported directories.

**Comment by a8m** [comment]
It's true that our focus is the CLI at this stage, but the reason we separated the two modules is to reduce the size/dependencies of the `ariga.io/atlas` module, but also to maintain the dev velocity without thinking about additional public API besides the CLI. 

Exporting the CLI functionally as a public API requires us to commit to these interfaces. We avoid this because many internal parts are evolving at this stage and exporting these parts may slow us down (CLI still maintains BC). One significant change we plan to make soon is to support extending Atlas using plugins - this may cause a lot of code deletion in the `cmd` package.

> The requirements are simple: we want the migrations to be handled by the application itself, not using any external out-of process tools.
> 
> Unfortunately I cannot go into more detail 

Maybe there are specific parts that can potentially go out to unblock you, but I'll love to discuss this on Discord or Meet to understand the context and the scope of work, as this is not in my roadmap at all at the moment. If you can't share more details, that's fine too - you can revisit Atlas in the future, and I hope it may be useful for you then. 

Thanks for the discussion. Closing, but please feel free to join the [Discord](https://discord.gg/zZ6sWVg6NT), and we can take it from there.

**Comment by ceresdarkmatter** [comment]
@a8m just out of curiosity - what extra info would you require? the request was simple - make all the CLI functionality available in the go library / module, there is literally nothing else besides this that would potentially make this work for us.
What else is there to discuss?
