### ISSUE TITLE
Implementation of RevisionReadWriter interface for postgresql

### ISSUE THREAD

**Issue by sachinsahoo11** [ariga/atlas#1352]
I am working on versioned migrations for my project and couldn't find any default implementation of RevisionReadWriter for postgresql for using Executor. Is there any other better way of applying the migrations file on DB?

**Comment by a8m** [comment]
Hey @sachinsahoo11 👋
The implementation resides on `cmd/atlas`. You can and should use the `atlas` CLI to execute migrations files using the `atlas migrate apply` command. We've added various guides to support migration execution in different deployments on the Atlas website; check them out: https://atlasgo.io/guides/deploying/intro.

Please, let me know if you still need help, or I can close this one. I'm available also on our [Discord](https://discord.gg/zZ6sWVg6NT) 😃

**Comment by sachinsahoo11** [comment]
Yes, I saw the CLI way but I was looking to do it within a service which would run and apply the migrations

**Comment by a8m** [comment]
What platform do you use for deployment? Kubernetes, ECS, etc.

**Comment by sachinsahoo11** [comment]
ECS

**Comment by a8m** [comment]
OK, tagging here @rotemtam, which is the deployment expert 😎

**Comment by sachinsahoo11** [comment]
https://github.com/ariga/atlas/pull/750 it seems to have been implemented for mysql already

**Comment by rotemtam** [comment]
hi @sachinsahoo11 

I understand you're trying to use Atlas in-process with a Go application. While I understand the motivation for this, we currently advise taking a different approach for deploying schema migrations to production environments. You can read a bit about our approach, and why we believe it's better not to run migrations in server initialization [here](https://atlasgo.io/guides/deploying/intro#running-migrations-on-server-initialization).

In addition, Atlas was built with the intention of being used by projects in many languages, outside the Go ecosystem, which is why the API we currently support in the CLI. Because of this decision we place some components which we prefer not to commit to their API and implementation in an `internal/` directory. 

To deploy schema migrations to an application on ECS, what we advise is:
1. During CI, build a container image based on Atlas, containing your migraitons. Guide [here](https://atlasgo.io/guides/deploying/image)
2. During deployment, your ECS task definition should include a container running your migrations image, and have your main application start after the migration container completes successfully. This can be done using [Container Dependency](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/example_task_definitions.html#example_task_definition-containerdependency) settings. 

This is similar in principle to using an [Init Container with Kubernetes](https://atlasgo.io/guides/deploying/k8s-init-container)

I plan to add a full example on how to do this, but I hope these points offer some guidance. 

Closing this, please re-open if you need more assistance.
