### ISSUE TITLE
sqlite: uint64 unsupported

### ISSUE THREAD

**Issue by michaeladler** [ariga/atlas#1448]
It seems that atlas cannot properly handle `uint64` columns when using sqlite3. 

## Reproduction Steps

Generate sqlite table using uint64 (this is from golang-migrate btw):

```sql
CREATE TABLE schema_migrations (version uint64,dirty bool);
```

Dump schema:

```bash
$ atlas schema inspect -u "sqlite://test.db" > sqlite.hcl
```

The file `sqlite.hcl` looks as follows:

```
table "schema_migrations" {
  schema = schema.main
  column "version" {
    null = true
    type = sql("uint64")
  }
  column "dirty" {
    null = true
    type = bool
  }
}
schema "main" {
}
```

Apply schema:

```bash
$ atlas schema apply -u sqlite://test2.db --to file://sqlite.hcl
Error: create table "schema_migrations": sqlite: unsupported type: "uint64"
```

**Comment by a8m** [comment]
Hey @michaeladler 👋 
`uint64` is not a valid type affinity in SQLite. You can read about it here: https://www.sqlite.org/datatype3.html

Having said that, Atlas still supports some type-names that are commonly used by popular ORMs outside (e.g., `bool` and `json`). Would you mind explaining why you use `uint64` rather than just `integer`?

**Comment by michaeladler** [comment]
@a8m Thanks, it works!
