### ISSUE TITLE
Pretty print / format generated SQL

### ISSUE THREAD

**Issue by mnahkies** [ariga/atlas#1474]
Currently when generating SQL using `migrate diff` the output is generally a single line per statement.

To make this output easier to code review, I think it would be nice if `atlas` could run a code formatter over the file prior to hashing, such that we get output like:
```sql
CREATE TABLE my_table (
  column1 TYPE,
  column2 TYPE
);
```
Instead of:
```sql
CREATE TABLE my_table (column1 TYPE, column2 TYPE);
```

I don't have an opinion on exactly which formatter. A quick google didn't turn up much for `golang` TBH

**Comment by a8m** [comment]
Thanks for suggesting this, @mnahkies. I like it, and I plan to add it to Atlas soon. 

I don't think we need an external formatter here because we build the SQL statements.

**Comment by a8m** [comment]
The issue was addressed, and it should be available in the latest binaries. See: https://atlasgo.io/versioned/diff#indented-sql

The `--format` flag was added to both `schema diff` and `migrate diff`, and same as the `schema inspect` command, you can use the `{{ sql . "  " }}` template to format the SQL statement indented with two spaces. e.g., 

```shell
# Indent SQL statements with two spaces.
atlas migrate diff create_users \
  --dir "file://migrations" \
  --to "file://schema.hcl" \
  --dev-url "docker://mysql/8/test" \
  --format '{{ sql . "  " }}'
```

```shell
# Indent SQL statements with tab.
atlas migrate diff create_users \
  --dir "file://migrations" \
  --to "file://schema.hcl" \
  --dev-url "docker://mysql/8/test" \
  --format '{{ sql . "\t" }}'
```
