### ISSUE TITLE
Does atlas have revert functionality when fail to do helm upgrade?

### ISSUE THREAD

**Issue by wangmir** [ariga/atlas#1485]
Same as the title.

I found this excellent tool, and I'm trying to study and make a strategy to utilize this tool on our project.
I saw these two pages to use atlas at CD of helm or k8s,

https://atlasgo.io/guides/deploying/helm
https://atlasgo.io/guides/deploying/k8s-init-container 

But I have a question about how can we revert partial changes when it fails to migrate the database. or when it fails to upgrade the version of its service (at the helm)?

Are there any examples of doing that?

**Comment by giautm** [comment]
From what I know, Altas can use transactions on some database engines if it is supported. So if the migration failed, it can roll back the changes on your DB.

You need to config the deployment only happen if the migration success (helm's post-upgrade). So if the migration fails, the deployment of the app should be stopped. Then you do some migration fixes on the database then retry the migrations. If migrations fail, it usually requires a manual fix.

**Comment by a8m** [comment]
> From what I know, Altas can use transactions on some database engines if it is supported. 

Adding to this the doc for `--tx-mode`: https://atlasgo.io/versioned/apply#transaction-configuration

**Comment by wangmir** [comment]
Ok. for the migration period itself can be atomically done with transactions. How about a rollback case which fails on the deployment of service, not the migration? 

When the database migration and deployment of new version of service is related, because the failure of service deployment will try to launch old version of the service, and it can cause collision with new version of database right?

Can we solve this kinds of situation using atlas too?

**Comment by wangmir** [comment]
I think this [link](https://atlasgo.io/versioned/apply#down-migrations) is answer this. I'll close the issue.

**Comment by rotemtam** [comment]
hey @wangmir 

I see you found the docs on how to revert changes in versioned migrations.

I would add that except for use cases where you can stop your application, migrate the database, and resume, migrations should generally be _backward compatible_. Because rolling out new versions of an application is a gradual process, and is never atomic with upgrading the database, old versions of your app should always be able to run with the next version of your database. 

If you're able to do this, this means that if your migrations succeed, but your application upgrade fails, you shouldn't need to revert the db change, just fix the app and roll forward. 

You can read about how a gradual schema change with zero down time can be planned  in @ronenlu 's [blogpost](https://entgo.io/blog/2022/12/01/changing-column-types-with-zero-downtime) on the topic.
