### ISSUE TITLE
Error: required flag(s) "dev-url" not set when following guide.

### ISSUE THREAD

**Issue by wangmir** [ariga/atlas#1487]
I'm trying to following the guide: https://atlasgo.io/versioned/apply#existing-databases

and I did the command,

```
atlas migrate diff my_baseline \
  --dir "file://migrations" \
  --to "postgres://postgres:pass@localhost:5432/database?sslmode=disable"
```

But when I enter this command, the error was like,

`Error: required flag(s) "dev-url" not set`.

I think the guide is incomplete for this usecase.

So I tested with different approach with following [quick introduction](https://atlasgo.io/getting-started/).

1. Inspect current schema as ddl
2. Edit schema ddl file with update
3. Call 
```
atlas migrate diff create_blog_posts \
  --dir "file://migrations" \
  --to "file://schema.hcl" \
  --dev-url "docker://mysql/8/example"
```

And in this case, I got this error. `taking database snapshot: sql/migrate: connected database is not clean: found schema "public"`

I'm confusing about the use case of this.. How can I get diff migration script from existing db?

**Comment by a8m** [comment]
Thanks for reporting this, @wangmir. 
This was fixed with https://github.com/ariga/atlas/pull/1488. You can see in this doc how to generate a diff from a database schema: https://atlasgo.io/versioned/diff#generate-migrations-from-database-schemas. However, if you need to migrate an existing database to Atlas, see the guide about baseline migrations: https://atlasgo.io/versioned/apply#existing-databases.
