### ISSUE TITLE
Generating an index migration ignores the CONCURRENTLY keyword

### ISSUE THREAD

**Issue by tgmendes** [ariga/atlas#1554]
## Context

We are using a hybrid approach between declarative and versioned migrations. We use the declarative schemas (in SQL) to be able to nicely integrate with [sqlc](https://sqlc.dev/), and also have a good overview of the database state, but we find it important to also have the migration files so we know exactly what changes are going to happen in the database and to be able to have linting in our PRs.

## Problem

If we want to create a migration to add an index concurrently, the generated migration file ignores the `CONCURRENTLY` keyword.
This could potentially cause us problems, because we might notice in a PR that the schema is well defined, but the migration file did not have the keyword there. If we were to have a very large table, this could be quite a serious incident for us.

## Example

Take this table (fake example for demo purposes):

```
CREATE TABLE "users" (
    "id" text NOT NULL,
    "email" text NULL,
    "account_number" text NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "id_email_idx" ON users("id", "email");
```

Running `atlas diff` generates the migration file file as expected:
```
-- Create "users" table
CREATE TABLE "public"."users" ("id" text NOT NULL, "email" text NULL, "account_number" text NULL, PRIMARY KEY ("id"));
-- Create index "id_email_idx" to table: "users"
CREATE UNIQUE INDEX "id_email_idx" ON "public"."users" ("id", "email");
```

**Now let's try adding an index concurrently** 

This is now the schema:
```
CREATE TABLE "users" (
    "id" text NOT NULL,
    "email" text NULL,
    "account_number" text NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "id_email_idx" ON users("id", "email");
CREATE INDEX CONCURRENTLY "user_account_number_key" ON users("account_number");
```

Running `atlas diff` generates the following:
```
-- Create index "user_account_number_key" to table: "users"
CREATE INDEX "user_account_number_key" ON "public"."users" ("account_number");
```

Ignoring the `CONCURRENTLY` keyword. 

## Notes

- Using `--edit` could be a possible interim solution, but it's still easy for someone to forget to add the flag. We could also always enforce it, but then we're creating friction when generating migrations.
- Relevant discord discussion [here](https://discord.com/channels/930720389120794674/933360123357839360/1088468739000905748)

@a8m - tagging you as requested :)

Let me know if I can help in any way.

Thank you!

**Comment by a8m** [comment]
Hey, @tgmendes 👋 
Thanks a lot for writing this. I actually took the time to think about this and implement some stuff that might help you at this stage. 

The declarative schema represents the current state of the database schema rather than its creation process. Therefore, options like `CONCURRENTLY` are ignored. However, in some situations, as you described, controlling the execution of schema changes is crucial to avoid application downtime. I believe the most common options are `CREATE INDEX CONCURRENTLY` and `DROP INDEX CONCURRENTLY` (are there any others?). To address this, I have added support for [such an analyzer](https://atlasgo.io/lint/analyzers#concurrent-index-policy-postgresql) in our migration linting integration.

I believe this solution resolves your issue but also ensures that the declarative model remains aligned with its purpose. In the future, we may consider extending `migrate diff` to support controlling how the changes (SQL file) should be generated, but that's a separate discussion.

Please, check out https://atlasgo.io/lint/analyzers#concurrent-index-policy-postgresql and let me know if I can close this issue.

**Comment by tgmendes** [comment]
Hey @a8m , this seems like a good compromise. I agree it would look somewhat strange to mix creation process details with a database state. 

I do have a question that may or may not be relevant for the discussion: what happens if you're using a pure declarative approach, and rely on Atlas to make all changes in the background. How are these indices added? Would you potentially run into problems with adding them concurrently or non-concurrently?

**Comment by disintegrator** [comment]
❤️ I think the linter is a great addition but it brings forth a cognitive dissonance from being able to specify CONCURRENTLY in schema definition but not having it come out in generated migration. Without the linter this can go unnoticed. This leads me to the question: what's the value in ignoring the various _features_ of defining schemas with SQL like `CONCURRENTLY`? The stated goal of "representing the current state of the database schema rather than its creation process" seems to mean that the CREATE INDEX statements are a contradiction. I'm not sure it's a net win but it would certainly help to learn more.

**Comment by a8m** [comment]
Thanks for the feedback, @disintegrator ❤️ 

> This leads me to the question: what's the value in ignoring the various _features_ of defining schemas with SQL like `CONCURRENTLY`?

Because the `CONCURRENTLY` option defines **how** the index should be created, rather than the fact that there's an index in this schema, this might be somewhat philosophical. However, the reason I prefer to keep this logic in the plan/diff policy is that Atlas schema can be defined in additional languages such as HCL, Go, and more soon, which means we need to support this there as well - and I prefer to avoid this.

Adding another section for the diff/plan policy in the `atlas.hcl` file sounds like a good compromise to me - you configure it once, and Atlas can follow these rules unless configured otherwise (e.g., in flags). What do you think about it?

@tgmendes, @disintegrator - I see you both work at the same place. If you're up for sharing more about your use case, I'd love to meet and get some feedback. Let me know if you're interested 🙏

**Comment by tgmendes** [comment]
We do indeed @a8m (we're even working on the same team). Personally, I'd be more than happy to have a chat 🙌  Feel free to DM me in Discord and we can arrange something.

I imagine you're suggesting something along the lines of:

```
env some-env {
  migration_policy {
    always_create_index_concurrently = true
  }
}
```

This would be a nice feature, which you could easily extend to other use cases in the future. The one caveat to be aware of is if you do not want this to happen for specific indices, and there might be a valid reason for that. 

I know you're trying to avoid this, but maybe adding this flag in the respective table `hcl` (or plain `sql`) wouldn't be that bad:
```
  index "idx_name" {
    columns = [
      column.name
    ]
    unique = true
    concurrent = true
  }
```

I have a feeling that as Atlas evolves you might start encountering a bunch of edge cases of things that are indeed a "how it gets created" (and not a "what's the state") that need to be fine tuned, and you may want to think of a mechanism to allow people to not only define where they want the DB to go but how to get there. For example, you could consider

```
table "users" {
  schema = schema.public

  ...

  creation_options = {
    create_indexes_concurrently = true
    some_other_option = false
  }

 index "idx_name" {
    columns = [
      column.name
    ]
    unique = true
    create_options {
      concurrent = false // override defaults for table for this index
    }
    
  }
```

I don't know if it's a good idea or not IMO, but something that may spark ideas on your end.

**Comment by tgmendes** [comment]
@a8m I'm going to close this issue for now.

I believe we have a good basis right now to avoid non-concurrent index creation, and any other improvements on this topic are more likely a longer term decision process. 

Thanks for the help and insights 👍

**Comment by a8m** [comment]
Hey @tgmendes and @disintegrator 👋 

As a follow-up to this discussion, we've added initial support for [_schema diff policy_](https://atlasgo.io/versioned/diff#diff-policy). You're welcome to give it a try and share your feedback.
