### ISSUE TITLE
atlas.sum mismatch between windows and linux systems

### ISSUE THREAD

**Issue by tankbusta** [ariga/atlas#1569]
While I was testing out Atlas Cloud, I noticed I was getting `checksum mismatch` errors. So I tried running the command `atlas migrate validate --dir "file://database/migrations"` to validate and was surprised when I didn't get an error code/response.

After discussion in discord, it seems I may be one of the only windows developers 😆. Joking aside, it seems that maybe windows line endings may be impacting the result of the migration checksum.

**Comment by masseelch** [comment]
Thanks @tankbusta, I will take a look.

**Comment by masseelch** [comment]
Hey @tankbusta, the happens due to the UTF-16 encoding of windows in the Terminal/PowerShell. This seems to be a problem a lot of other tools face on Windows as well and the common solution is to change the default encoding to UTF-8, which is what we recommend in this case as well. Is this a suitable solution for you as well?

**Comment by masseelch** [comment]
> I'd think the hashing algorithm should disregard new lines (and potentially whitespace) as they don't affect the schema

This is not entirely true, e.g. in:

```sql
insert into tbl (col) values ('linux has \n'), ('mac has \r'), ('windows has \r\n');
```

we cannot simply remove / replace / split on any new line char. This is why we hash on byte level. However, since we hash on byte level there should not be a mismatch between the hashes. Do you by any chance have git configured to handle the line endings based on the client? This would explain the mismatch, since your windows machine would send in CRLF based sum and git would change that to LF on checkout on Linux / CI.

**Comment by tankbusta** [comment]
Yeah I totally spaced out on the migration data use case. That makes sense.

I think the default behavior for git on windows is to enable core.autoclrf. I disabled it and it's working now

**Comment by masseelch** [comment]
> I think the default behavior for git on windows is to enable core.autoclrf. I disabled it and it's working now

Great to hear that. In that case, I think we can close this, right? Afterall, the current behavior of the sum-file is correct, agree?

**Comment by tankbusta** [comment]
Yep!
