### ISSUE TITLE
Generating migration for time field with default value is not working

### ISSUE THREAD

**Issue by Kurounin** [ariga/atlas#1968]
When using the versioned migration, for the following field
```go
field.Time("created_at").
	Immutable().
	Default(time.Now)
```
when running the command to generate a new migration file
```bash
atlas migrate diff add_created_at \
	  --dir "file://internal/migrations" \
	  --to "ent://internal/schema" \
	  --dev-url "docker://postgres/15/test?search_path=public"
```
the following migration is generated
```sql
-- Modify "test" table
ALTER TABLE "test" ADD COLUMN "created_at" timestamptz NOT NULL;
```
which is missing ` DEFAULT NOW()`.
If I manually add it, any subsequent migrations will try to `DROP DEFAULT` for that column.

**Comment by a8m** [comment]
Thanks for reporting this, @Kurounin. The `Default` option in Ent is set on the app-level for time and UUID fields. However in order to set the actual database default value, you can use the `entsql.Annotation`. See: https://github.com/ent/ent/blob/master/dialect/entsql/annotation.go#L185-L199

Closing, but please feel free to reopen an issue in the `ent/ent` repository in case you still need help with this.
