### ISSUE TITLE
[Question]: Using variables from `atlas.hcl` env inside CLI command

### ISSUE THREAD

**Issue by maslennikov** [ariga/atlas#1981]
Hello! Atlas newb here trying to evaluate this amazing software for our corporate toolset and processes. 

Situation: I have carefully crafted my `atlas.hcl` with all variables and [var. sources](https://atlasgo.io/atlas-schema/projects#data-sources) logic. And eventually I have my `local` env like that:
 ```
env "local" {
  src = var.src
  url = var.url
  dev = "docker://mysql/8"

  migration {
    dir = "file://migrations"
  }
}
```

## Problem

And having all that, when I want to use `atlas schema diff --env local ....`, I need to duplicate those values from config passing them via `--from`, `--to`. It looks cumbersome, especially when they were programmatically retrieved.

## Question

Is there any mechanism telling CLI script that I want to use current value of `url` from my `env "local"`? 

Imagine it could look something like this:
```sh
atlas schema diff --env local --from env://src --to env://url
```

**Comment by maslennikov** [comment]
@a8m you have answered my recent ticket blazingly fast, maybe you already know the answer? :)

**Comment by a8m** [comment]
Hey, @maslennikov!

The —to/—from cannot be read from config file, because the names/concepts are different between the two. From my experience, `schema diff` is a useful for running state comparisons, but those are mainly ad hoc and changing.

We might consider reading data source info from config file (as URL) in the future, but this is not supported atm.

**Comment by maslennikov** [comment]
Thank you!
