### ISSUE TITLE
arigaio/mysql Docker image for arm64

### ISSUE THREAD

**Issue by jacobwgillespie** [ariga/atlas#1997]
Hey, I'm running Atlas on a M1 MacBook with `--dev-url docker://mysql/8` - this uses the `arigaio/mysql:8` image which is only published for `linux/amd64`, so database operations are rather slow due to the emulation.

Would it be possible to publish this image for arm64 as well? I don't see a GitHub repo for that image, otherwise I could send a PR.

**Comment by a8m** [comment]
Hey @jacobwgillespie 👋 

This image was created to speed up the dev workflow as the standard image is much slower (database initialization happens on start instead of build).

You are welcome to contribute this change. Here are the relevant files:
- https://github.com/ariga/atlas/blob/master/.github/workflows/cd-docker-push-mysql_oss.yaml
- https://github.com/ariga/atlas/blob/master/.github/ops/mysql/Dockerfile

**Comment by jacobwgillespie** [comment]
Hey, thanks yeah I missed that they were defined here 👍 PR #1998 should enable `arm64` builds for the images that support them.
