### ISSUE TITLE
Support for applying missed migrations

### ISSUE THREAD

**Issue by lorefnon** [ariga/atlas#2034]
Hello, thanks for creating and maintaining atlas. 

I am curious if there is a plan to enable the built in migration runner to run migrations that are behind the latest version but were not applied (perhaps through a config option).

To outline why this is useful, please consider following scenario which uses versioned workflow: 

- main branch is at version 1 and all changes so far are applied to db
- In branch A: My collaborator modifies the schema over time and generate migrations version 2 & 3
- In branch B: I modify the schema and generate migration version 4
- Branch B is merged first and deployed - as part of deployment version 4 is applied to db
- Now when branch A is merged, when running migrations atlas identifies that latest version is 4 and db is already at version 4 and hence there is nothing do. Versions 2 & 3 get ignored which is undesirable. 

If I want to ensure all migrations are always run (even if the order is different), can that be done without using some other migration runner.

**Comment by a8m** [comment]
Hey @lorefnon and thanks for the kind words 🙏.

We're following this principle for a good reason: Atlas adopts the "linear migration history" approach. We believe this makes the migration execution process simpler (without complex computing), predictable (ensuring files execute in the right order, no matter where, when, and how many of them), and reversible. This mindset mirrors the difference between Git's merge-commits and linear history. The former can be extremely challenging to handle (rollbacks) when troubleshooting issues in production.

Regarding the scenario you described, that's exactly why Atlas features a built-in [migration integrity file](https://atlasgo.io/concepts/migration-directory-integrity) (`atlas.sum`), a linter, and a CI setup for verification - we prevent such issues in advance. The `atlas.sum` file ensures that changes cannot be merged into the master branch unless they're in sync with the latest state of the migration directory. If they're not, they'll encounter a merge conflict, and a rebase is required - this might cause users to change their migrations in case they are conflicted with the master state. This process ensures that developers do not add schema changes that either conflict with others or fail due to incorrect schema logic (the linter checks other stuff, btw).

Another essential characteristic of the migration directory is that it should be _"replayable"_, where files are executed in sequence. If we opted for a random or arbitrary order, this invariant would no longer hold true. It's an essential requirement that Atlas's core depends on. In the end, the migration directory represents a schema graph of objects (like tables) and their dependencies (other tables or objects) that must be built in the right order. If we can't determine the correct order to construct this graph, the migration history loses its purpose, becoming merely a collection of files. The result of this is that automatic migration planning cannot work anymore (e.g., `migrate diff`). 

I can elaborate further on why this is essential for Atlas and its capabilities as a schema management tool, in case you have any specific questions. But the bottom line is that the proposed option will not be added to Atlas, at least not in the foreseeable future. I appreciate the suggestion and I hope you understand this isn't an arbitrary decision; it comes from our experience managing database schemas. We believe this approach has served both us and our users well until now.

**Comment by lorefnon** [comment]
Hello Ariel,

Thank you for the detailed explanation.

However I am slightly lost now on how team collaboration is expected to
happen effectively in scenarios like the one I described.

I don't mind adapting our workflow, but let's say we want to merge a branch
that got left behind for a while, a rebase alone is not adequate right ? We
would have to update the timestamps in the migration files too which would
then have to skipped for local databases where the changes have already
been applied?

**Comment by lorefnon** [comment]
So I revise my proposal a bit: What if the migration runner provided us control over the sequence of the migrations ? 

We have a list of migrations of atlas.sum, and migrations generated afresh get appended to the list as usual. However we can resequence this file when resolving conflicts (similar in spirit to git's interactive rebase). 

The sequence in this file serves as the canonical linear sequence and migration apply always goes from the index of current version further down in the sequence defined in atlas.sum independent of migration timestamps. And if a migration in this sequence is already applied atlas prints a warning that their local database state may deviate from canonical schema but otherwise does nothing.

**Comment by a8m** [comment]
Hey! Sorry for the delayed response. I’m off for a few days, and will answer right after.
