### ISSUE TITLE
Option to `SET ROLE TO` before executing query

### ISSUE THREAD

**Issue by hectorj-thetreep** [ariga/atlas#2176]
Hi!

One way of managing user privileges in postgres is to have a few well-defined `NOLOGIN` roles, and to set users as `NOINHERIT` while granting them those roles. (described here: https://kumom.io/articles/postgreSQL-privileges#alternative-solution-noinherit)

It means that to use a role's privileges, the user needs to `SET ROLE TO xxx;` in each session.

Is there a way to do this with Atlas (I mean the `SET ROLE`, not the users&roles&privileges setup) ? I didn't find one.

If not, is this a feature you would consider? I think it would be best in the URL query so it could be different for each connection (url vs dev_url)

**Comment by rotemtam** [comment]
Hi @hectorj-thetreep, 
Thanks for reaching out. We currently don't have a solution for this. We are working on comprehensive support for managing roles, privileges, RLS, etc. I guess this might be built as part of that. There are no timelines yet, unfortunately.

**Comment by wyardley** [comment]
Just found this thread by searching... same problem / question here.

I find with PostgreSQL in general, managing roles is very tricky, and using a virtual role means that you'd want to execute `SET ROLE xyz;` before running commands; otherwise you either have to manually run a `REASSIGN OWNED BY ...` after (side note: this doesn't always work well on GCP CloudSQL or other database services where you may not have a true superuser role).

So even if it's not the perfect long-term solution, having the ability to have some kind of arbitrary SQL hook or SQL file that gets executed before a set of commands would be really handy (I guess when using raw SQL schemas, maybe it would work to have that command in the first SQL file that gets read; not sure if anyone's tried that before?)

**Comment by rotemtam** [comment]
Did you see https://atlasgo.io/versioned/apply#migration-hooks ?

**Comment by wyardley** [comment]
> Did you see https://atlasgo.io/versioned/apply#migration-hooks ?

No, I didn't, but that's exactly what I was looking for. Thanks! I did look, but obviously wasn't searching for the right thing 🤦 🙊

**Comment by rotemtam** [comment]
It's a recent addition, so there's not many mentions for it, we should do a better job at making it accessible!

Feel free to join our Discord and share how it went 🙏

**Comment by hectorj-thetreep** [comment]
Perfect, I feel like we can close this issue. Thanks!

**Comment by wyardley** [comment]
@rotemtam actually, my use case is for declaratively managed schema - I'm assuming that migration-hooks will not work to insert something before managing the schema declaratively with the `atlas schema apply` command?

**Comment by hectorj-thetreep** [comment]
Indeed, the hooks don't seem to apply to all commands (tested with an `atlas schema clean`)
