### ISSUE TITLE
Hash error when generated using migration files using CRLF line separator

### ISSUE THREAD

**Issue by andre-bisa** [ariga/atlas#2195]
All the times I have to create the hash I need to be sure that all the migration files are in LF (\n) and not in CRLF (\r\n). Windows by default set the files to CRLF but it fails the hash check in our pipelines.

Is it possible to modify the hash calculating function so that CRLF and LF generates the same hash?

**Comment by masseelch** [comment]
Hey @andre-bisa, we currently don't have official support for windows. For local dev on Windows, we advise to use either our provided [docker image](https://hub.docker.com/r/arigaio/atlas) or use [WSL](https://learn.microsoft.com/en-us/windows/wsl/install). 

> Is it possible to modify the hash calculating function so that CRLF and LF generates the same hash?

Sadly, it is not as straighforward as this, since we need to maintain backwards compatability. If we drop the line separator from the hash calculation, we'd render all checksum invalid that have been created prior to this change.
