### ISSUE TITLE
Some ORM migration scripts encountered when having below codes

### ISSUE THREAD

**Issue by althaf004** [ariga/atlas#2266]
1. `\set ddl_schema dcp_lib` -  _Error pq: syntax error at or near "\"_
2. ` SET search_path TO :'extensions_schema',:'ddl_schema'`  - _pq: syntax error at or near ":"_
3. `CREATE SCHEMA IF NOT EXISTS :ddl_schema;` - _pq: syntax error at or near ":"_

**Comment by a8m** [comment]
Hey, @althaf004 👋 

`\set` is not part of the PostgreSQL - it's a `psql` command. See: https://www.postgresql.org/docs/current/app-psql.html#APP-PSQL-META-COMMAND-SET

**Comment by althaf004** [comment]
remaining 2 & 3

**Comment by a8m** [comment]
Same thing. `:` is for placeholders (variables substitution).

What tool did you use for generating these migrations? Is it a schema or a migration file? Also, `search_path` is set on the URL (connection string) or the `schema(s)` flag/option rather than on the migration/schema file itself - it's not used in migration files nor a schema file.

**Comment by althaf004** [comment]
i have used used https://github.com/netspective-labs/sql-aide to generate the migration  script.
[miga8m.zip](https://github.com/ariga/atlas/files/13330469/miga8m.zip)

**Comment by a8m** [comment]
Thanks for sharing, @althaf004.

_SQL Aide_ uses a Typescript template for its migrations. This is not supported by Atlas by default, but you can write a small script to support this using the `external_schema` data source. See: https://atlasgo.io/atlas-schema/external
