### ISSUE TITLE
LTREE support

### ISSUE THREAD

**Issue by kevinmichaelchen** [ariga/atlas#2277]
Hey - This is a very enjoyable project so far!

I was wondering if LTREEs are supported / if support might be coming in the future.

I tried an LTREE like this:

```
column "path" {
  null = false
  type = ltree
}
```

but got:

```
Unknown column.type; There is no type named "ltree"
```

**Comment by a8m** [comment]
Hey @kevinmichaelchen! I'm glad to hear you're enjoying the project.

Most extension types are not available in HCL by default, but you can use them as follows:

```hcl
column "path" {
  null = false
  type = sql("ltree")
}
```
We're still deliberating on the right 'import' for extensions and their usage in the schema, which is why they're not supported at the moment.

**Comment by a8m** [comment]
Closing as this duplicate of #520.
