### ISSUE TITLE
Atlas Wants to Generate a Migration for the Schema Revision Table

### ISSUE THREAD

**Issue by davidwarshaw-fintron** [ariga/atlas#2661]
First, thanks for this project!
I'm using the versioned migrations flow on postgres, using the following steps:
1. I manually create an initial migration, `baseline.sql`, in my migrations dir.
2. I run `atlas migrate hash` to create `atlas.sum`, which creates a sum file with two lines.
  ```
    atlas migrate hash \
      --dir file://$MIGRATIONS_DIR
  ```
3. I run `atlas migrate apply` to apply it the DB, which works without issue.
  ```
     atlas migrate apply \
      --dir file://$MIGRATIONS_DIR \
      --url $DB_CONNECTION_STRING
  ```
4. I check the `atlas_schema_revisions` table in the DB, it's in the public schema and has one row, the migration I just ran.
5. I run `atlas migrate diff`. I expect no changes to be present, as nothing has changed. Atlas produces a new migration to create the schema revision table!
  ```
    atlas migrate diff test-migration \
      --dir file://$MIGRATIONS_DIR \
      --dev-url $DEV_DB_DOCKER_STRING \
      --to $DB_CONNECTION_STRING \
      --format '{{ sql . "  " }}'
  ```

```
> cat $MIGRATIONS_DIR/20240403155435_test-migration.sql

-- Create "atlas_schema_revisions" table
CREATE TABLE "public"."atlas_schema_revisions" (
  "version" character varying NOT NULL,
  "description" character varying NOT NULL,
  "type" bigint NOT NULL DEFAULT 2,
  "applied" bigint NOT NULL DEFAULT 0,
  "total" bigint NOT NULL DEFAULT 0,
  "executed_at" timestamptz NOT NULL,
  "execution_time" bigint NOT NULL,
  "error" text NULL,
  "error_stmt" text NULL,
  "hash" character varying NOT NULL,
  "partial_hashes" jsonb NULL,
  "operator_version" character varying NOT NULL,
  PRIMARY KEY ("version")
);

```

Postgres version:
```
PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
```

Atlas version:
```
atlas version v0.21.0
https://github.com/ariga/atlas/releases/tag/v0.21.0
```

Possibly related to: https://github.com/ariga/atlas/issues/2612

**Comment by a8m** [comment]
Hey, @davidwarshaw-fintron 👋 

The `--to` flag represents the desired state of the schema. When running `migrate diff`, Atlas compares the desired state (`--to`) to your migration directory, and generates all necessary DDLs to bring the migration directory (current state) to the state of the desired schema.

The desired state can be an SQL file/directory, HCL, ORM or a database URL. Although the database URL is one of the options, it should not be the same one you applied migrations on it. Why? there can be one desired state, but multiple instances of it (result of `migrate apply`). This also avoid cases like this, because like you said, `atlas_schema_revisions` is not part of the desired state.

**Comment by davidwarshaw-fintron** [comment]
I see. The workflow I'm trying to support is one where devs are using ent to auto migrate their local dev databases, but are then creating versioned migrations (containing manual fixes that are sometimes necessary) that they check in.

**Comment by a8m** [comment]
> I'll try using the ent schema files as the --to target instead as described here: https://entgo.io/docs/versioned-migrations/#generating-versioned-migration-files

OK, feel free to join our Discord if you need more support with it.
