### ISSUE TITLE
allow customizing non-linear changes lint behaviour

### ISSUE THREAD

**Issue by sincraianul** [ariga/atlas#2833]
Currently the lint command checks for non-linear changes and reports a warning. It would be ideal to be able to customize the behaviour such that non-linear changes cause the lint to error out, like so:

```hcl
lint {
  non_linear {
    error = true
  }
}
``` 

cc. @a8m

**Comment by a8m** [comment]
Hey! Just update that the issue was resolved. See this doc for config example: https://atlasgo.io/lint/analyzers#non-linear-changes

![image](https://github.com/ariga/atlas/assets/7413593/9377a3b8-c867-4d52-a5de-5380193e9133)

Example output:

![image](https://github.com/ariga/atlas/assets/7413593/65a321d3-9842-4650-a772-e69450ba9c25)
