### ISSUE TITLE
Customizing DDL generation in HCL

### ISSUE THREAD

**Issue by x80486** [ariga/atlas#2868]
## Description

I'm test-driving Atlas for a new Go project with a PostgreSQL database. I'm planning to use it through the _versioned migration workflow_. Here is a snippet from my `schema.hcl`:

```hcl
schema "main" {
  charset = "UTF8"
}

table "table_name" {
  schema = schema.main

  column "id" {
    default = sql("gen_random_uuid()")
    type    = uuid
  }

  primary_key {
    columns = [column.id]
  }
}
```

When I execute `atlas migrate diff some-description --env dev` against an empty [Dev Database](https://atlasgo.io/atlas-schema/sql#dev-database) PostgreSQL instance, I get the following generated SQL:

```sql
-- Drop schema named "public"
DROP SCHEMA "public" CASCADE;
-- Add new schema named "main"
CREATE SCHEMA "main";
-- Create "table_name" table
CREATE TABLE "main"."table_name" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), PRIMARY KEY ("id"));
```

There are a few issues here. Atlas _inferred_ that the `public` schema should be dropped — probably because it's a PostgreSQL database and this may be a popular approach/decision, but I really never declared anything closer to that. The other issue I see is creating the `main` schema; this is a process that's usually done beforehand (with the required roles) as part of the database setup, so using `CREATE SCHEMA "main"` without `IF NOT EXISTS` may cause issues in higher environments, but it's a must for local development.

Is there a way for Atlas to automatically generate the correct DDL in such cases? Specifically:

- Avoid dropping the `public` schema.
- Use `CREATE SCHEMA IF NOT EXISTS "main";` for schema creation to ensure idempotence.

I'm aware that I can manually modify the generated SQL by removing the `DROP SCHEMA "public" CASCADE;` statement, appending `IF NOT EXISTS` to the `CREATE SCHEMA` statement...and finally running `atlas migrate hash`. However, I would prefer a way to configure this behavior directly in the HCL file to avoid manual intervention.

## Additional Context

- Atlas version: `atlas unofficial version v0.23.0` (installed using Nix packages)
- PostgreSQL version: `16.1`

**Comment by a8m** [comment]
> There are a few issues here. Atlas inferred that the public schema should be dropped — probably because it's a PostgreSQL database and this may be a popular approach/decision, but I really never declared anything closer to that.

That's because the `public` schema is not defined in your HCL schema, and your [dev-url is scoped to a database connection](https://atlasgo.io/concepts/url#scope) (which contains the auto-created `public` schema). The solution for this, is to just tell Atlas you manage a single schema and ignore all the rest. 
<img width="1111" alt="image" src="https://github.com/ariga/atlas/assets/7413593/0f632003-aaf6-4f9a-a235-cbccb9faa1f3">

**Comment by a8m** [comment]
> Use CREATE SCHEMA IF NOT EXISTS "main"; for schema creation to ensure idempotence.

No, there's no policy for this (intentionally). Only the `public` schema is created with the `IF NOT EXISTS` clause due to the Postgres implicit behavior. 

If you manage a database (multiple schemas) with Atlas, the schemas should be created by it, and it's the ~only tool that should manage it. If you're managing a specific schema (the connection URL is scoped to that schema), Atlas is not responsible for creating it, the SQL statements are not qualified (`t` instead of `s`.`t`), and can be executed on ~any schema. You can still ofc edit the migration file to contain the `IF NOT EXISTS` clause.

**Comment by x80486** [comment]
I see. I didn't realize the `schema` object was required...and I was trying different settings.

Thanks for your help! Atlas is quite an interesting product :ok_hand:
