### ISSUE TITLE
Support implicit names for PG indexes and constraints

### ISSUE THREAD

**Issue by net** [ariga/atlas#3117]
When creating indexes and constraints via DDL, Postgres (and other relational DBs) will generate a name for them if none is specified.

```sql
create table foo (
  bar integer unique
);
```

```
            Table "public.foo"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 bar    | integer |           |          |
Indexes:
  "foo_bar_key" UNIQUE CONSTRAINT, btree (bar)
```

```sql
create table foo (
  bar integer primary key
);
create table qux (
  bar integer references foo
);
```

```
                Table "public.qux"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 bar    | integer |           |          |
Foreign-key constraints:
    "qux_bar_fkey" FOREIGN KEY (bar) REFERENCES foo(bar)
```

These auto-generated names follow a convention. If Atlas HCL supported these implicit names, it would make defining new indexes and constraints a fair amount easier, and would reduce the risk when working with developers unfamiliar with these conventions that unconventional names make it into the DB.

```hcl
table "qux" {
  ...

  foreign_key {
    columns     = [column.bar]
    ref_columns = [table.foo.column.bar]
  }
}
```

Here's a list of Postgres's naming conventions: https://til.cybertec-postgresql.com/post/2019-09-02-Postgres-Constraint-Naming-Convention

**Comment by a8m** [comment]
We actually prevent this by design and I don't see a way we change this. The generated/implicit names rely on the database state and might be different between runs/databases. The schema (as code concept) is supposed to represent the same schema graph, irrelevant to the state of the database (the dev and the real one).  

A few examples (we countered in the past) which these "naming conventions" didn't work for us: columns/tables were renamed, names were taken by other objects, etc:

<img width="1053" alt="image" src="https://github.com/user-attachments/assets/2ce2f52f-f2ee-4cb3-93d7-6bccff0d1a3c">
<img width="1053" alt="image" src="https://github.com/user-attachments/assets/5cc7c28a-44c6-4de8-a586-586ec94673af">

**Comment by net** [comment]
I suspected that was the reason, but I think there's a solution in having Atlas generate the names following the same convention as the DB, and erroring if two generated names would conflict. That wouldn't support keeping indexes across column renames, but properly renaming a production column is non-trivial already.

**Comment by a8m** [comment]
Since we had been there before with Ent, which was too buggy and unpredictable (especially for long object names) - there's no convention just for the object names, as the numbers play an important role for keeping generated names unique (references to examples from Postgres source to explain the logic: [makeObjectName](https://github.com/postgres/postgres/blob/4d8489f4f1fa86a99e6db0ea702911e1cf92fa81/src/backend/commands/indexcmds.c#L2414), [ChooseRelationName](https://github.com/postgres/postgres/blob/4d8489f4f1fa86a99e6db0ea702911e1cf92fa81/src/backend/commands/indexcmds.c#L2500)).

As I mentioned earlier, I currently don't see a situation where we would reverse this decision. The correctness of Atlas is the important factor here. 

Thanks for the feedback and the suggestion 🙏
