### ISSUE TITLE
Add "auto approve" option to `schema apply` command

### ISSUE THREAD

**Issue by ericyd** [ariga/atlas#519]
**Type**

Feature request

**Background**

My interest in Atlas is to streamline our CI flow. We currently prepare a database in our CI environment and run migrations sequentially before our tests run. This takes about 25-30 seconds whereas `atlas schema apply` takes a fraction of a second. However, for this to work in a CI environment, there needs to be a command line option to "auto-approve" the schema application.

**Details**

* Add a flag to the `schema apply` command that approves the schema application without prompting for user input

**Comment by a8m** [comment]
Hey hey @ericyd 👋 

cc'ing @rotemtam and @yonidavidson as they wanted to add this, and they can help you contribute this change to atlas if you like (should be pretty simple). Thanks 🙏

**Comment by rotemtam** [comment]
hey @ericyd ,

thanks for the feedback! 

I would love to see this added to the `schema apply` command. It should be a quick fix, if you would like to contribute to the project, this can be a great start! If so, ping me on our discord server.  Otherwise we will probably add it in next week's release.

In the meantime, you can do something like:
```
echo "\n" | atlas schema apply ...
```

**Comment by ericyd** [comment]
seems like a very promising project, I'm excited about the work that has already been put in. I'll try to make time tomorrow to pursue a fix and I'll reach out on Discord before I do

**Comment by rotemtam** [comment]
That's great! Looking forward to working on this with you
