### ISSUE TITLE
can not create default NULL with timestamp for mysql

### ISSUE THREAD

**Issue by calvin2021y** [ariga/atlas#738]
mysql need this SQL for timestamp type:

```sql
CREATE TABLE `test` (
  `id` int(11) NOT NULL,
  `update_time` timestamp NULL DEFAULT NULL
) 
```

without ` DEFAULT NULL`, it will not work.

atlas can not handle this:
```hcl
table "test" {
	schema  = schema.test
	column "id" {
		type = int
		auto_increment = true
		null = false
	}
	column "update_time" {
		type = timestamp
		default = null
		null = true
	}
	primary_key {
		columns = [column.id]
	}
}
schema "test" {
	charset = "utf8mb4"
	collate = "utf8mb4_unicode_ci"
}
```

error:
```sh
Error: schemahcl: failed decoding: schemahcl: unsupported type "cty.DynamicPseudoType"
```

**Comment by a8m** [comment]
Hey @calvin2021y and thanks for reporting this issue 👋 
Can you share what's the MySQL version you use?

AFAIK, omitting the `DEFAULT` clause is equal to adding it with `DEFAULT NULL`, so removing the `default = null` should solve the issue here. See:

![image](https://user-images.githubusercontent.com/7413593/165479519-74ffef10-a444-40ab-ae18-9da2ef140c1b.png)

![image](https://user-images.githubusercontent.com/7413593/165479599-07e25091-c33e-4532-8c0b-f39299eba7fe.png)

**Comment by calvin2021y** [comment]
You are right,  I am not check the SQL carefully.

Mysql 5.7.37.

```sql
CREATE TABLE `test` (
  `id` int(11) NOT NULL,
  `update_time` timestamp
) 
```

after create table export to this:
```sql
CREATE TABLE `test` (
  `id` int(11) NOT NULL,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```
