### ISSUE TITLE
No way to break glass and use not-yet-implemented types

### ISSUE THREAD

**Issue by achew22** [ariga/atlas#868]
I was expecting to be able to set the type of a column to a custom SQL expression by using the `sql` command.

But with the input: 

```
  column "duration" {
    null    = false
    type    = sql("interval")
    comment = "The duration that the reservation will last for."
  }
```

I get the error output:

```
Error: reverse alter table "mytable": postgres: unsupported type: "interval"
```

The error coming from

https://github.com/ariga/atlas/blob/89197145cc46bd66ba330f01ac18b5e236effb97/sql/postgres/convert.go#L129-L130

However, based on this testcase I would have expected it to work:

https://github.com/ariga/atlas/blob/89197145cc46bd66ba330f01ac18b5e236effb97/internal/integration/cockroach_test.go#L331

Could you maybe point me in a direction for this one?

**Comment by achew22** [comment]
I guess I should include that I ran `go install ariga.io/atlas/cmd/atlas@latest` before doing this, and that I'm targeting CockroachDB

**Comment by achew22** [comment]
I fiddled with this a little bit more and it seems that while the first apply works. Later applies are unable to read the schema from the DB and give this error.

**Comment by a8m** [comment]
Hey @achew22 👋 
Thanks for reporting this. This `interval` type was [partially](https://github.com/ariga/atlas/blob/master/sql/postgres/inspect.go#L256-L258) implemented. I'll finish its support soon (today or at the weekend) and I'll update you.

**Comment by a8m** [comment]
Hey @achew22! Just to let you know that I finished the implementation for `interval` types. We'll release a new version soon, but you can get the latest master version using the following command:

```
go install ariga.io/atlas/cmd/atlas@master
```

Closing, but please, let me know if you still need help with it. Thanks 🙏

**Comment by achew22** [comment]
Does this mean that if you use `sql("unsupportedtype")` it will work now as well?

**Comment by a8m** [comment]
The issue was specifically for `interval` types because it was partially implemented. We support user-defined types atm but it's not optimal (i.e. `sql("...")`) and I plan to tackle it after we'll finish the CI support for Atlas. Please, feel free to open an issue if something is not working for you.

**Comment by rotemtam** [comment]
Hey @achew22 
I think what @a8m meant was that the mechanism for unsupported types (ie sql("type")) works, in this edge case, interval wasn't exactly an unsupported type rather an implementation that was missing some detail which is why you ran into this issue.
I've successfully used Atlas with PostGIS types, for example, where Atlas isn't familiar with them so it uses the sql() mechanism to pass them around.
HTH

**Comment by a8m** [comment]
Hey @achew22, please use atlas@master instead of atlas@latest.

**Comment by achew22** [comment]
Ah, that seems to have fixed it. Thanks!
